data:
  augmentation:
  - Noise
  - TimeShift
  duration: 3
  sr: 22050
model:
  dropout: 0.5
  l2: 0.001
  name: CNN_Optimized_v2
training:
  batch_size: 16
  callbacks:
  - EarlyStopping
  - ReduceLROnPlateau
  epochs: 60
